load('data.mat')
tblOpts = {'header',{'Grid Size','Matrix Size',...
    'iters','time','iters','time','time'},'format',{'%6.0f','%6.0f','%4.0i'...
    ,'%3.4f','%4.0i','%3.4f','%3.4f'},'align','center','delim','|',...
    'printRow',true};

for ii = 1:size(data,1);
    table('',data(1:ii,:),tblOpts{:}...
        ,'finalRow',ii == size(data,1));
end